apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: gateway-ms
  name: gateway-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gateway-ms
    spec:
      containers:
      - image: northamerica-northeast1-docker.pkg.dev/tienda-microservices-432723/image-registry/gateway-ms
        name: gateway-ms
        env:
        - name: PORT
          value: "3000"
        - name: NATS_SERVERS
          value: "nats://nats"
        resources: {}
status: {}
